apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xeksclusters.aws.example.com
spec:
  group: aws.example.com
  names:
    kind: XEKSCluster
    plural: xeksclusters
  claimNames:
    kind: EKSCluster
    plural: eksclusters
  connectionSecretKeys:
    - kubeconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: EKS cluster configuration parameters
                  properties:
                    region:
                      type: string
                      description: AWS region for the EKS cluster
                      default: us-west-2
                    vpcCidrBlock:
                      type: string
                      description: CIDR block for the VPC
                      default: "10.0.0.0/16"
                    publicSubnet1Cidr:
                      type: string
                      description: CIDR block for public subnet 1
                      default: "10.0.1.0/24"
                    publicSubnet2Cidr:
                      type: string
                      description: CIDR block for public subnet 2
                      default: "10.0.2.0/24"
                    privateSubnet1Cidr:
                      type: string
                      description: CIDR block for private subnet 1
                      default: "10.0.3.0/24"
                    privateSubnet2Cidr:
                      type: string
                      description: CIDR block for private subnet 2
                      default: "10.0.4.0/24"
                    k8sVersion:
                      type: string
                      description: Kubernetes version for EKS
                      default: "1.28"
                    nodeInstanceType:
                      type: string
                      description: EC2 instance type for worker nodes
                      default: t3.medium
                    desiredNodeCount:
                      type: integer
                      description: Desired number of worker nodes
                      default: 2
                    minNodeCount:
                      type: integer
                      description: Minimum number of worker nodes
                      default: 1
                    maxNodeCount:
                      type: integer
                      description: Maximum number of worker nodes
                      default: 5
                    addons:
                      type: object
                      description: EKS add-ons configuration
                      properties:
                        vpcCni:
                          type: object
                          description: VPC CNI add-on configuration
                          properties:
                            enabled:
                              type: boolean
                              description: Enable VPC CNI add-on
                              default: true
                            version:
                              type: string
                              description: VPC CNI add-on version
                              default: "v1.12.6-eksbuild.1"
                            configuration:
                              type: object
                              description: VPC CNI configuration parameters
                              properties:
                                warmPodTarget:
                                  type: integer
                                  description: Number of warm pods to target
                                  default: 2
                                warmIpTarget:
                                  type: integer
                                  description: Number of warm IPs to target
                                  default: 2
                        coreDns:
                          type: object
                          description: CoreDNS add-on configuration
                          properties:
                            enabled:
                              type: boolean
                              description: Enable CoreDNS add-on
                              default: true
                            version:
                              type: string
                              description: CoreDNS add-on version
                              default: "v1.10.1-eksbuild.6"
                            configuration:
                              type: object
                              description: CoreDNS configuration parameters
                              properties:
                                computeType:
                                  type: string
                                  description: Compute type for CoreDNS
                                  default: "EC2"
                        kubeProxy:
                          type: object
                          description: kube-proxy add-on configuration
                          properties:
                            enabled:
                              type: boolean
                              description: Enable kube-proxy add-on
                              default: true
                            version:
                              type: string
                              description: kube-proxy add-on version
                              default: "v1.28.1-eksbuild.1"
                            configuration:
                              type: object
                              description: kube-proxy configuration parameters
                              properties:
                                mode:
                                  type: string
                                  description: Proxy mode
                                  default: "iptables"
                                iptables:
                                  type: object
                                  description: iptables configuration
                                  properties:
                                    masqueradeAll:
                                      type: boolean
                                      description: Masquerade all traffic
                                      default: false
                        ebsCsiDriver:
                          type: object
                          description: EBS CSI driver add-on configuration
                          properties:
                            enabled:
                              type: boolean
                              description: Enable EBS CSI driver add-on
                              default: true
                            version:
                              type: string
                              description: EBS CSI driver add-on version
                              default: "v1.26.1-eksbuild.1"
                            configuration:
                              type: object
                              description: EBS CSI driver configuration parameters
                              properties:
                                mountOptions:
                                  type: string
                                  description: Mount options for EBS volumes
                                  default: "nfsvers=4.1"
                  required:
                    - region
              required:
                - parameters
            status:
              type: object
              properties:
                vpcId:
                  type: string
                  description: ID of the created VPC
                clusterEndpoint:
                  type: string
                  description: EKS cluster API endpoint
                clusterName:
                  type: string
                  description: Name of the EKS cluster
                costEstimate:
                  type: object
                  description: Estimated monthly and yearly costs for the cluster
                  properties:
                    currency:
                      type: string
                      description: Currency code for cost estimates
                      default: "USD"
                    monthly:
                      type: number
                      description: Estimated monthly cost
                    yearly:
                      type: number
                      description: Estimated yearly cost
                    breakdown:
                      type: object
                      description: Cost breakdown by component
                      properties:
                        ec2Instances:
                          type: object
                          properties:
                            monthly:
                              type: number
                            yearly:
                              type: number
                        eksControlPlane:
                          type: object
                          properties:
                            monthly:
                              type: number
                            yearly:
                              type: number
                        natGateway:
                          type: object
                          properties:
                            monthly:
                              type: number
                            yearly:
                              type: number
                        ebsVolumes:
                          type: object
                          properties:
                            monthly:
                              type: number
                            yearly:
                              type: number
                        dataTransfer:
                          type: object
                          properties:
                            monthly:
                              type: number
                            yearly:
                              type: number
                    lastUpdated:
                      type: string
                      description: Timestamp when cost estimate was last updated
