# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint

# Default state for all rules
default: true

# MD013 - Line length
MD013:
  line_length: 200
  code_blocks: false
  tables: false

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true

# MD033 - Inline HTML (allow for badges and images)
MD033: false

# MD041 - First line should be a top-level heading
MD041: true

# MD046 - Code block style
MD046:
  style: fenced
