apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: cert-manager
spec:
  forProvider:
    chart:
      name: cert-manager
      repository: https://charts.jetstack.io
      version: "v1.14.4"
    namespace: cert-manager
    values:
      installCRDs: true
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
      webhook:
        replicaCount: 1
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      cainjector:
        replicaCount: 1
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      prometheus:
        enabled: true
        servicemonitor:
          enabled: false
  providerConfigRef:
    name: default
