apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: external-dns
spec:
  forProvider:
    chart:
      name: external-dns
      repository: https://kubernetes-sigs.github.io/external-dns
      version: "1.14.3"
    namespace: external-dns
    values:
      provider: aws
      aws:
        region: us-west-2
        zoneType: public
      policy: sync
      registry: txt
      txtOwnerId: my-cluster
      domainFilters:
        - example.com
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      serviceAccount:
        create: true
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-dns-role
  providerConfigRef:
    name: default
