apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: metrics-server
spec:
  forProvider:
    chart:
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: "3.12.0"
    namespace: kube-system
    values:
      replicas: 2
      args:
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 400Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
  providerConfigRef:
    name: default
