apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: nginx-ingress
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.11.3"
    namespace: ingress-nginx
    values:
      controller:
        replicaCount: 2
        service:
          type: LoadBalancer
        metrics:
          enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
  providerConfigRef:
    name: default
