apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters-azure.compute.example.com
  labels:
    provider: azure
    crossplane.io/claim-name: cluster
spec:
  compositeTypeRef:
    apiVersion: compute.example.com/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: common-parameters
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.tags
                toFieldPath: spec.forProvider.tags
        resources:
          # ===================
          # Resource Group
          # ===================
          - name: resource-group
            base:
              apiVersion: resources.azure.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                forProvider:
                  location: West US 2
            patches:
              - type: PatchSet
                patchSetName: common-parameters
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-rg"
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.networkId

          # ===================
          # Virtual Network
          # ===================
          - name: virtual-network
            base:
              apiVersion: network.azure.upbound.io/v1beta1
              kind: VirtualNetwork
              spec:
                forProvider:
                  addressSpace:
                    - "10.0.0.0/16"
            patches:
              - type: PatchSet
                patchSetName: common-parameters
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.networking.vpcCidr
                toFieldPath: spec.forProvider.addressSpace[0]
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-vnet"
              - type: FromCompositeFieldPath
                fromFieldPath: resource-group.status.atProvider.name
                toFieldPath: spec.forProvider.resourceGroupName

          # ===================
          # Subnets
          # ===================
          - name: public-subnet
            base:
              apiVersion: network.azure.upbound.io/v1beta1
              kind: Subnet
              metadata:
                labels:
                  access: public
              spec:
                forProvider:
                  addressPrefix: "10.0.1.0/24"
                  virtualNetworkNameSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: common-parameters
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.networking.subnetCidrs[0]
                toFieldPath: spec.forProvider.addressPrefix
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-public-subnet"
              - type: FromCompositeFieldPath
                fromFieldPath: resource-group.status.atProvider.name
                toFieldPath: spec.forProvider.resourceGroupName

          - name: private-subnet
            base:
              apiVersion: network.azure.upbound.io/v1beta1
              kind: Subnet
              metadata:
                labels:
                  access: private
              spec:
                forProvider:
                  addressPrefix: "10.0.2.0/24"
                  virtualNetworkNameSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: common-parameters
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.networking.subnetCidrs[1]
                toFieldPath: spec.forProvider.addressPrefix
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-private-subnet"
              - type: FromCompositeFieldPath
                fromFieldPath: resource-group.status.atProvider.name
                toFieldPath: spec.forProvider.resourceGroupName

          # ===================
          # AKS Cluster
          # ===================
          - name: aks-cluster
            base:
              apiVersion: containerservice.azure.upbound.io/v1beta1
              kind: KubernetesCluster
              spec:
                forProvider:
                  dnsPrefix: aks-cluster
                  defaultNodePool:
                    - name: default
                      nodeCount: 3
                      vmSize: Standard_D2s_v3
                      osDiskSizeGB: 30
                      osType: Linux
                      enableAutoScaling: true
                      minCount: 1
                      maxCount: 5
                  identity:
                    - type: SystemAssigned
                  networkProfile:
                    - networkPlugin: azure
                      serviceCidr: "10.96.0.0/12"
                      dnsServiceIP: "10.96.0.10"
                      dockerBridgeCidr: "172.17.0.1/16"
            patches:
              - type: PatchSet
                patchSetName: common-parameters
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.dnsPrefix
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-aks"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.nodeCount
                toFieldPath: spec.forProvider.defaultNodePool[0].nodeCount
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.nodeInstanceType
                toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
              - type: FromCompositeFieldPath
                fromFieldPath: resource-group.status.atProvider.name
                toFieldPath: spec.forProvider.resourceGroupName
              - type: FromCompositeFieldPath
                fromFieldPath: virtual-network.status.atProvider.name
                toFieldPath: spec.forProvider.networkProfile[0].virtualNetworkName
              - type: FromCompositeFieldPath
                fromFieldPath: private-subnet.status.atProvider.name
                toFieldPath: spec.forProvider.networkProfile[0].subnetNames[0]
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.networking.serviceCidr
                toFieldPath: spec.forProvider.networkProfile[0].serviceCidr
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.fqdn
                toFieldPath: status.clusterEndpoint
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.name
                toFieldPath: status.clusterName
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.defaultNodePool[0].name
                toFieldPath: status.nodeGroupIds[0]
